version: '3.1'

services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_quizz
    ports:
      - 3308:3306
  app:
    build:
      dockerfile: ./docker/Dockerfile
      context: .
    ports:
      - 7001:80
    depends_on:
      - "db"
    env_file:
      - .env
    environment:
      DATABASE_URL: mysql://root:root@db:3306/my_quizz?serverVersion=5.7
    volumes:
      - ./:/var/www/html/

  adminer:
    image: adminer
    ports:
      - 8080:8080